sprint5 project
kazantipovna/Sprint_5 pull request #1
Opened 2023-11-22 15:48 UTC by kazantipovna

проект по спринту 5

2023-11-23 15:18 UTC, kadirovgm requested changes

2023-11-23 15:18 UTC, kadirovgm commented on .DS_Store
нужно исправить: что это за файл? он не относится к проекта, лучше удалить либо добавить в .gitignore

2023-11-23 15:18 UTC, kadirovgm commented on .idea/.gitignore
нужно исправить: что это за папка? он не относится к проекта, лучше удалить либо добавить в .gitignore

2023-11-23 15:18 UTC, kadirovgm commented on README.md
> +
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов, используя разметку Markdown

2023-11-23 15:18 UTC, kadirovgm commented on tests/conftest.py
> +
нужно исправить: почему эти методы и данные находятся в conftest.py ? 

conftest.py - должен хранить только фикстуры

2023-11-23 15:18 UTC, kadirovgm commented on tests/conftest.py
> +
Предлагаю вынести тестовые данные в файл data.py и сгруппировать их там по классам

2023-11-23 15:18 UTC, kadirovgm commented on tests/conftest.py
> +
А все методы для генерации данных вынести в файл helpers.py

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_constructor.py
> +    driver = webdriver.Chrome()
Нужно исправить: необходимо добавить самую важную фикстуру, отвечающую за setup и teardown в файл condtest.py

пример:

```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()

```

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_constructor.py
> +    driver.quit()
Нужно исправить: давай в тестах не держать teardown и setup методы, мы должны стараться минимизировать повторяющиеся строки кода

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_constructor.py
> +    driver.find_element(By.XPATH, './/span[text()="Соусы"]').click()
Нужно исправить: локаторы предлагаю не держать в тестах и вынести в начало файла как класс Locators(), чтобы не повторять одни и те же локаторы в каждом тесте, а переиспользовать их

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_lk.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(conftest.email)
нужно исправить: локатор стоит оптимизировать, он выглядит не особо надежным из-за вложенностей div

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_lk.py
> +    driver.find_element(By.XPATH, './/fieldset[2]/div/div/input').send_keys(conftest.password)
нужно исправить: оптимизировать локатор

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_lk.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(conftest.email)
нужно исправить: оптимизировать локаторы

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_lk.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(conftest.email)
можно лучше: советую написать функцию и вынести ее в файл helpers.py, который будет заполнять поля для авторизации, тогда в тестах не придется повторять эти лаги, а лишь вызвать нужную функцию

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_lk.py
> +
Можно лучше: для легкого понимания кода предлагаю перед названием тестовых методов описывать коротко о чем тест, лучше в формате "докстринг"

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_lk.py
> +    assert driver.current_url == 'https://stellarburgers.nomoreparties.site/account/profile'
Нужно исправить: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_login.py
> +    assert driver.find_element(By.XPATH, './/button[text()="Оформить заказ"]').is_displayed()
отлично!

2023-11-23 15:18 UTC, kadirovgm commented on tests/test_login.py
> +    driver.find_element(By.XPATH, './/fieldset[2]/div/div/input').send_keys(password)
Нужно исправить: локаторы стоит оптимизировать

2023-11-27 16:59 UTC, kazantipovna commented on .DS_Store
++

2023-11-27 16:59 UTC, kazantipovna commented on .idea/.gitignore
++

2023-11-27 17:00 UTC, kazantipovna commented on README.md
> +
++

2023-11-27 17:01 UTC, kazantipovna commented on tests/conftest.py
> +
++ вынесла локаторы, методы и списки в helpers.py, в helpers.py остались только переменные для корректного логина

2023-11-27 17:03 UTC, kazantipovna commented on tests/test_constructor.py
> +    driver = webdriver.Chrome()
++

2023-11-27 17:03 UTC, kazantipovna commented on tests/test_lk.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(conftest.email)
++

2023-11-27 17:04 UTC, kazantipovna commented on tests/test_lk.py
> +
++ "докстринг" попыталась использовать, но в некоторых местах оставляла комменты

2023-11-27 17:05 UTC, kazantipovna commented on tests/test_lk.py
> +    assert driver.current_url == 'https://stellarburgers.nomoreparties.site/account/profile'
++ убрала везде проверку урлов, оставила проверки кнопки или заголовка

2023-11-27 17:05 UTC, kazantipovna commented on tests/test_login.py
> +    driver.find_element(By.XPATH, './/fieldset[2]/div/div/input').send_keys(password)
++

2023-11-27 19:25 UTC, kadirovgm requested changes

2023-11-27 19:25 UTC, kadirovgm commented on tests/conftest.py
> +def driver_register():
Нужно исправить: у тебя эти три фикстуры ничем не отличаются, кроме как открытием разных ссылок - это иррациональное использование фикстур.

Корректнее будет оставить лишь одну фикстуру driver, а уже на страницу /register или /login переходить в самих тестах, либо создать функции helper-ы, которые будут уметь переходить по разным ссылкам

в общем такое повторение кода - не уместно, предлагаю оставить одну фикстуру driver

2023-11-27 19:25 UTC, kadirovgm commented on tests/data.py
> +name = 'Julia'
можно лучше: тестовые данные стоит сгруппировать по классам

2023-11-27 19:25 UTC, kadirovgm commented on tests/helpers.py
> +    LOCATOR_LOGIN_BNT1 = By.XPATH, './/button[text()="Войти в аккаунт"]' # кнопка "Войти в аккаунт" с главной
Можно лучше: незачем все переменные локатор называть, начиная "LOCATOR_"

и так понятно, что это локаторы, так как они находятся в классе Locators

2023-11-27 19:25 UTC, kadirovgm commented on tests/helpers.py
> +class Locators:
можно лучше: обычно локаторы дежрат в одноименном файле, например, locators.py

2023-11-27 19:25 UTC, kadirovgm commented on tests/helpers.py
> +short_pass = [''.join(random.sample(string.ascii_letters + string.digits, 1)),
можно лучше: скорее это должны быть в файле data.py

2023-11-27 19:25 UTC, kadirovgm commented on tests/helpers.py
> +def login_fields_set(driver, email, password):
отлично!

2023-11-27 19:25 UTC, kadirovgm commented on tests/test_registration.py
> +@pytest.mark.parametrize('password', [helpers.short_pass[0], helpers.short_pass[1], helpers.short_pass[2],
нужно исправить: зачем тратить время на такие данные? когда можно проверить лишь границы значений, а именно: 0, 1, 5

2023-11-27 19:25 UTC, kadirovgm commented on tests/test_registration.py
> +@pytest.mark.parametrize('email', [helpers.unform_email[0], helpers.unform_email[1],
тоже можно сократить количество данных используя тест дизайн (граничные значения)

2023-11-27 21:13 UTC, kazantipovna commented on tests/conftest.py
> +def driver_register():
++ по ссылкам перехожу в тестах

2023-11-27 21:13 UTC, kazantipovna commented on tests/helpers.py
> +    LOCATOR_LOGIN_BNT1 = By.XPATH, './/button[text()="Войти в аккаунт"]' # кнопка "Войти в аккаунт" с главной
++

2023-11-27 21:14 UTC, kazantipovna commented on tests/helpers.py
> +class Locators:
++

2023-11-27 21:14 UTC, kazantipovna commented on tests/helpers.py
> +short_pass = [''.join(random.sample(string.ascii_letters + string.digits, 1)),
++

2023-11-27 21:15 UTC, kazantipovna commented on tests/test_registration.py
> +@pytest.mark.parametrize('password', [helpers.short_pass[0], helpers.short_pass[1], helpers.short_pass[2],
++ именно в этом тесте 1 и 5, 0 проверяется в тесте test_registration_without_pass

2023-11-27 21:15 UTC, kazantipovna commented on tests/test_registration.py
> +@pytest.mark.parametrize('email', [helpers.unform_email[0], helpers.unform_email[1],
++ сократила

2023-11-29 20:23 UTC, kadirovgm approved these changes

2023-11-30 07:17 UTC, merged